using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class Tile : MonoBehaviour
{
    #region Attributes
    public TileTypes _type; //The type of the tile
    public Building _building; //The building on this tile
    public List<Tile> _neighborTiles; //List of all surrounding tiles. Generated by GameManager
    public int _coordinateHeight; //The coordinate on the y-axis on the tile grid (not world coordinates)
    public int _coordinateWidth; //The coordinate on the x-axis on the tile grid (not world coordinates)


    [SerializeField] private GameObject UpperLeftEdge;
    [SerializeField] private GameObject UpperRightEdge;
    [SerializeField] private GameObject RightEdge;
    [SerializeField] private GameObject LowerRightEdge;
    [SerializeField] private GameObject LowerLeftEdge;
    [SerializeField] private GameObject LeftEdge;


    #endregion

    #region Enumerations
    public enum TileTypes { Empty, Water, Sand, Grass, Forest, Stone, Mountain }; //Enumeration of all available tile types. Can be addressed from other scripts by calling Tile.Tiletypes
    #endregion


    //upperCenterEdge.gameObject.SetActive(false);
    //TODO actually disable or enable edges according to the logic
    public void setEdges(bool[] edgeValue)
    {
        //edgeValue[0]

        this.UpperLeftEdge.gameObject.SetActive(!edgeValue[0]);
        this.UpperRightEdge.gameObject.SetActive(!edgeValue[1]);

        this.RightEdge.gameObject.SetActive(!edgeValue[2]);


        this.LowerRightEdge.gameObject.SetActive(!edgeValue[3]);
        this.LowerLeftEdge.gameObject.SetActive(!edgeValue[4]);
        this.LeftEdge.gameObject.SetActive(!edgeValue[5]);


    }

    //This class acts as a data container and has no functionality
}
